apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-group-controller.resource-group.ten1010.io
webhooks:
  - name: resource-group-controller.resource-group.ten1010.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: <CA_BUNDLE>
      service:
        namespace: resource-group-controller
        name: resource-group-controller
        path: /admissionreviews
        port: 8080
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  [ "CREATE", "UPDATE" ]
        resources:   ["pods", "replicationcontrollers"]
        scope: "*"
      - apiGroups: [ "batch" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "cronjobs", "jobs" ]
        scope: "*"
      - apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "daemonsets", "deployments", "replicasets", "statefulsets" ]
        scope: "*"
    sideEffects: None
    timeoutSeconds: 10
---
